
server:
  port: 9101

spring:
  servlet:
    multipart:
      max-file-size: 25MB
  application:
    name: ms-users
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/sis-323}
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/sis-323}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none

keycloak:
  auth-server-url: http://localhost:8080
  autodetect-bearer-only: true
  credentials:
    secret: CalOb9h83bEQEGYqaduEg0p4CFzaNnEa
    realm: sis-323
    resource: pm-backend

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}


token:
  converter:
    principal-attribute: preferred_username
    resource-id: sis-323
