
server:
  port: 8081

spring:
  application:
    name: ms-users
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sis-323}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    jpa:
      hibernate:
        ddl-auto: none

keycloak:
  auth-server-url: http://localhost:8080
  autodetect-bearer-only: true
  credentials:
    secret: CalOb9h83bEQEGYqaduEg0p4CFzaNnEa
    realm: sis-323
    resource: pm-backend

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

