# @no-cookie-jar
POST http://localhost:9100/api/v1/users/student
Content-Type: application/json

{
  "modalityId": 1,
  "name": "Papu",
  "lastName": "Gomezs",
  "motherLastName": "Hola",
  "email": "gomez@email.com",
  "phoneNumber": "283293289",
  "password": "password",
  "group": "professors",
  "username": "papu1"


}
###

POST http://localhost:9100/api/v1/users/professor
Content-Type: application/json

{
"modalityId": 1,
"name": "Pedro",
"lastName": "Picapiedra",
"motherLastName": "si",
"email": "pedro@email.com",
"phoneNumber": "1002321",
"password": "password",
"username": "pedro_pica"


}



